# 提权操作
ansible_become: true
command_warnings: false

_host_architecture_groups:
  x86_64: amd64
  aarch64: arm64
  armv7l: arm
host_architecture: >-
  {%- if ansible_architecture in _host_architecture_groups -%}
  {{ _host_architecture_groups[ansible_architecture] }}
  {%- else -%}
  {{ ansible_architecture }}
  {%- endif -%}

_host_distribution_groups:
  uos: debian
host_distribution: >-
  {%- if ansible_distribution in _host_distribution_groups -%}
  {{ _host_distribution_groups[ansible_distribution] }}
  {%- else -%}
  {{ ansible_distribution }}
  {%- endif -%}

host_distribution_release: >-
  {%- if (ansible_distribution_release == 'n/a') or (ansible_distribution_release is not defined) or (ansible_distribution_release == '') -%}
  buster
  {%- else -%}
  {{ ansible_distribution_release }}
  {%- endif -%}

epel_yum_repo: >-
  {%- if ansible_distribution_major_version is version('8', '<') -%}
  http://mirrors.aliyun.com/epel/$releasever/$basearch
  {%- else -%}
  https://mirrors.aliyun.com/epel/$releasever/Everything/$basearch
  {%- endif -%}

# 节点时区
timezone: Asia/Shanghai
# 是否跳过节点资源校验
skip_verify_node: false
# 默认apiserver负载类型
lb_mode: nginx

# 默认kube_dns_domain
kube_dns_domain: cluster.local
# 默认 lb_kube_apiserver_port
lb_kube_apiserver_port: 8443
# 当前节点ip
CURRENT_HOST_IP: "{% if hostvars[inventory_hostname]['ansible_host'] is defined %}{{ hostvars[inventory_hostname]['ansible_host'] }}{% else %}{{ inventory_hostname }}{% endif %}"
# 默认使用kube-proxy的 'iptables' 模式，可选 'ipvs' 模式(experimental)
kube_proxy_mode: "iptables"
# NodePort端口范围
kube_service_node_port_range: 30000-32767

# container 运行时类型
container_manager: containerd

# # 自定义hosts记录
# # 举例：
# custom_hosts:
#   "127.0.0.1": 
#   - "one.domain.custom.local"
#   - "tow.domain.custom.local"
custom_hosts: {}