- name: 添加 Kubernetes yum 仓库
  yum_repository:
    name: kubernetes
    description: Kubernetes Repository
    baseurl: "{{ kubernetes_yum_repo }}"
    enabled: no
    gpgcheck: no
    state: present

- name: "安装 kubeadm-{{ kube_upgrade_version }}"
  yum:
    name: 
    - "kubeadm-{{ kube_upgrade_version }}"
    state: present
    enablerepo: kubernetes

- include_tasks: common.yml

- name: "安装 kubelet-{{ kube_upgrade_version }} kubectl-{{ kube_upgrade_version }}"
  yum:
    name: 
    - "kubectl-{{ kube_upgrade_version }}"
    - "kubelet-{{ kube_upgrade_version }}"
    state: present
    enablerepo: kubernetes