#!/bin/bash
set -eux;

yum install -y yum-utils createrepo epel-release

# 添加docker源
yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

# 添加kubernetes源
cat <<EOF | tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
enabled=1
gpgcheck=0
repo_gpgcheck=0
gpgkey=https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
EOF

# 创建缓存目录
mkdir -p /kubernetes
cd /kubernetes

repotrack nmap-ncat
repotrack jq
repotrack git
repotrack perl
repotrack nss
repotrack nss-pem
repotrack lvm2
repotrack curl
repotrack htop
repotrack iotop
repotrack socat
repotrack ipset
repotrack sysstat
repotrack ipvsadm
repotrack nfs-utils
repotrack yum-utils
repotrack net-tools
repotrack libseccomp
repotrack conntrack-tools
repotrack bash-completion
repotrack device-mapper-persistent-data
repotrack docker-ce-19.03.13
repotrack docker-ce-cli-19.03.13
repotrack containerd.io-1.3.7
repotrack kubeadm-1.20.0
repotrack kubectl-1.20.0
repotrack kubelet-1.20.0

createrepo --update ./
tar -czvf kubernetes-1.20.0.tar.gz *.rpm repodata