#!/bin/bash

docker pull setzero/ansible:2.8.5-nginx-1.17.6-alpine
docker pull registry.cn-shanghai.aliyuncs.com/c7n/openresty:1.15.8.3-alpine
docker pull registry.cn-shanghai.aliyuncs.com/c7n/dashboard:v2.0.0-rc6 
docker pull registry.cn-shanghai.aliyuncs.com/c7n/metrics-scraper:v1.0.3
docker pull registry.aliyuncs.com/google_containers/kube-proxy:v1.16.8 
docker pull registry.aliyuncs.com/google_containers/kube-apiserver:v1.16.8 
docker pull registry.aliyuncs.com/google_containers/kube-scheduler:v1.16.8 
docker pull registry.aliyuncs.com/google_containers/kube-controller-manager:v1.16.8 
docker pull registry.aliyuncs.com/google_containers/coredns:1.3.1 
docker pull registry.aliyuncs.com/google_containers/etcd:3.4.3-0 
docker pull registry.aliyuncs.com/google_containers/metrics-server-amd64:v0.3.6 
docker pull registry.aliyuncs.com/google_containers/pause:3.2 
docker pull registry.aliyuncs.com/google_containers/tiller:v2.16.3 
docker pull registry.cn-shanghai.aliyuncs.com/c7n/flannel:v0.12.0-amd64
docker pull registry.cn-shanghai.aliyuncs.com/c7n/nginx-ingress-controller:0.30.0 

docker save \
    setzero/ansible:2.8.5-nginx-1.17.6-alpine \
    registry.cn-shanghai.aliyuncs.com/c7n/openresty:1.15.8.3-alpine \
    registry.cn-shanghai.aliyuncs.com/c7n/dashboard:v2.0.0-rc6 \
    registry.cn-shanghai.aliyuncs.com/c7n/metrics-scraper:v1.0.3 \
    registry.aliyuncs.com/google_containers/kube-proxy:v1.16.8 \
    registry.aliyuncs.com/google_containers/kube-apiserver:v1.16.8 \
    registry.aliyuncs.com/google_containers/kube-scheduler:v1.16.8 \
    registry.aliyuncs.com/google_containers/kube-controller-manager:v1.16.8 \
    registry.aliyuncs.com/google_containers/coredns:1.3.1 \
    registry.aliyuncs.com/google_containers/etcd:3.4.3-0 \
    registry.aliyuncs.com/google_containers/metrics-server-amd64:v0.3.6 \
    registry.aliyuncs.com/google_containers/pause:3.2 \
    registry.aliyuncs.com/google_containers/tiller:v2.16.3 \
    registry.cn-shanghai.aliyuncs.com/c7n/nginx-ingress-controller:0.30.0 \
    registry.cn-shanghai.aliyuncs.com/c7n/flannel:v0.12.0-amd64 | gzip -1 > /kubernetes/kubernetes-1.16.8.tar