#!/bin/bash

docker pull dockerhub.azk8s.cn/setzero/ansible:2.8.5-nginx-1.17.6-alpine
docker pull dockerhub.azk8s.cn/library/nginx:1.17.8-alpine 
docker pull dockerhub.azk8s.cn/kubernetesui/dashboard:v2.0.0-rc5 
docker pull dockerhub.azk8s.cn/kubernetesui/metrics-scraper:v1.0.3
docker pull gcr.azk8s.cn/google_containers/kube-proxy:v1.16.7 
docker pull gcr.azk8s.cn/google_containers/kube-apiserver:v1.16.7 
docker pull gcr.azk8s.cn/google_containers/kube-scheduler:v1.16.7 
docker pull gcr.azk8s.cn/google_containers/kube-controller-manager:v1.16.7 
docker pull gcr.azk8s.cn/google_containers/coredns:1.3.1 
docker pull gcr.azk8s.cn/google_containers/etcd:3.4.3-0 
docker pull gcr.azk8s.cn/google_containers/metrics-server-amd64:v0.3.6 
docker pull gcr.azk8s.cn/google_containers/pause:3.1 
docker pull gcr.azk8s.cn/kubernetes-helm/tiller:v2.14.3 
docker pull quay.azk8s.cn/coreos/flannel:v0.11.0-amd64
docker pull quay.azk8s.cn/kubernetes-ingress-controller/nginx-ingress-controller:0.29.0 

docker save \
    dockerhub.azk8s.cn/setzero/ansible:2.8.5-nginx-1.17.6-alpine \
    dockerhub.azk8s.cn/library/nginx:1.17.8-alpine \
    dockerhub.azk8s.cn/kubernetesui/dashboard:v2.0.0-rc5 \
    dockerhub.azk8s.cn/kubernetesui/metrics-scraper:v1.0.3 \
    gcr.azk8s.cn/google_containers/kube-proxy:v1.16.7 \
    gcr.azk8s.cn/google_containers/kube-apiserver:v1.16.7 \
    gcr.azk8s.cn/google_containers/kube-scheduler:v1.16.7 \
    gcr.azk8s.cn/google_containers/kube-controller-manager:v1.16.7 \
    gcr.azk8s.cn/google_containers/coredns:1.3.1 \
    gcr.azk8s.cn/google_containers/etcd:3.4.3-0 \
    gcr.azk8s.cn/google_containers/metrics-server-amd64:v0.3.6 \
    gcr.azk8s.cn/google_containers/pause:3.1 \
    gcr.azk8s.cn/kubernetes-helm/tiller:v2.14.3 \
    quay.azk8s.cn/kubernetes-ingress-controller/nginx-ingress-controller:0.29.0 \
    quay.azk8s.cn/coreos/flannel:v0.11.0-amd64 | gzip -1 > /kubernetes/kubernetes-1.16.7.tar