name: Anolis8 packages for arm64 
on:
  workflow_call:
    secrets:
      OSS_TOKEN:
      OSS_USERNAME:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Install and configure minio client
      run: |
        sudo curl -sSLo /usr/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc
        sudo chmod +x /usr/bin/mc
        mc alias set oss https://oss.choerodon.com.cn ${{ secrets.OSS_USERNAME }} ${{ secrets.OSS_TOKEN }}

    - name: Download packages for arm64
      run: |
        docker system prune -a -f --volumes 
        docker run --rm \
            --platform linux/arm64 \
            -v $PWD:/kubeadm-ha \
            -w /kubeadm-ha \
            openanolis/anolisos:8 \
            /bin/bash offline/download-rpm.sh anolis8
        /bin/bash offline/download-others.sh arm64
        tar -czvf packages.tgz packages

    - name: Upload arm64 artifact to oss
      id: oss
      run: |
        mc cp --json packages.tgz oss/kubeadm-ha/anolis8/kubernetes-1.29.6-anolis8-arm64.tgz 2>&1 | tee oss.log
        target=$(cat oss.log | jq -r 'select(.target)|.target')
        echo "::warning file=kubernetes-packages::https://oss.choerodon.com.cn/${target#*/}"
